packages:
  - apps/*
  - packages/*
  - tools/*

catalogMode: prefer

catalog:
  "@babylonjs/core": ^9.20.0
  "@hono/node-server": ^2.1.0
  "@types/node": ^24.13.3
  "@types/react": ^19.2.18
  "@types/react-dom": ^19.2.4
  "@vercel/analytics": ^2.0.1
  "@vercel/speed-insights": ^2.0.0
  "@vitejs/plugin-react": ^6.0.5
  hono: ^4.13.1
  postgres: ^3.4.9
  react: ^19.2.8
  react-dom: ^19.2.8
  typescript: ^7.0.2
  vercel: ^58.10.0
  vite: npm:@voidzero-dev/vite-plus-core@0.2.9
  vite-plus: 0.2.9
overrides:
  vite: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
allowBuilds:
  esbuild: true
