import type { ExoplanetProfile, StarKind, StarProfile } from "@exora/contracts";

/**
 * Bumped whenever the deterministic derivation of a visual recipe changes in a way that
 * would alter the output for existing catalog objects. Consumers that persist or cache a
 * recipe should key on (worldgenVersion, objectId) so a version bump invalidates old caches
 * instead of silently mixing recipes generated by different rules.
 */
export const WORLDGEN_VERSION = 2;

export type Rgb = readonly [red: number, green: number, blue: number];

/**
 * A cautious visual bucket for a planet, distinct from the coarse `PlanetKind` used for
 * catalog filtering. `unknown` is a legitimate, common outcome — it means the catalog did not
 * report enough physical properties to prefer one visual family over another, not that the
 * object is exotic.
 */
export type PlanetVisualClass =
  | "gas_giant"
  | "hot_gas_giant"
  | "ice"
  | "ice_giant"
  | "lava"
  | "ocean_candidate"
  | "rocky"
  | "unknown";

export type RockyPaletteFamily =
  | "basaltic-dark"
  | "carbon-dark"
  | "desert-tan"
  | "ice-blue"
  | "iron-rich"
  | "lava-black-red"
  | "oxidized-red"
  | "silicate-neutral"
  | "sulfuric-yellow";

export type GiantPaletteFamily =
  | "cream-brown"
  | "cyan-ice"
  | "hot-dark-red"
  | "methane-blue"
  | "neutral-cloud"
  | "pale-gold"
  | "ultrahot-red-brown";

/**
 * MEASURED: values read verbatim from the NASA Exoplanet Archive / SIMBAD catalog row, with no
 * math applied. `null` means the catalog simply did not report the field — never coerced to a
 * fallback number here, so downstream code can tell "unknown" apart from "zero".
 */
export interface PlanetMeasuredProperties {
  equilibriumTemperatureKelvin: number | null;
  hostLuminosityLogSolar: number | null;
  hostMassSolar: number | null;
  hostRadiusSolar: number | null;
  hostTemperatureKelvin: number | null;
  massEarth: number | null;
  massJupiter: number | null;
  radiusEarth: number | null;
  radiusJupiter: number | null;
  semiMajorAxisAu: number | null;
}

/**
 * DERIVED: obtained by combining MEASURED fields with well-established physics (unit
 * conversion, inverse-square insolation). A DERIVED field is still a fact about the object, not
 * a guess — it is `null` whenever an input it needs is missing, rather than being backfilled
 * with a fallback.
 */
export interface PlanetDerivedProperties {
  /** g/cm^3, only populated when both a measured radius and mass exist; Earth ≈ 5.51. */
  bulkDensityGCm3: number | null;
  /** Stellar insolation relative to Earth's, only populated when host luminosity and orbital
   * distance are both measured. */
  insolationEarthRelative: number | null;
  /** Radius/mass in Earth units, coalesced across the radius/mass unit pairs and given a sane
   * default only when the catalog reported neither — used purely to size the visual, never to
   * imply a measurement exists. */
  massEarthEffective: number;
  radiusEarthEffective: number;
}

/**
 * INFERRED: a cautious, probabilistic read on likely appearance, built on top of MEASURED and
 * DERIVED properties. Never a claim of scientific fact — `confidence` reflects how much catalog
 * data actually backed the inference (more known physical properties -> higher confidence), and
 * the `*Likelihood` fields are heuristic tendencies in [0, 1], not measurements.
 */
export interface PlanetInferredProperties {
  confidence: "low" | "medium" | "high";
  iceLikelihood: number;
  oceanLikelihood: number;
  paletteFamily: GiantPaletteFamily | RockyPaletteFamily;
  visualClass: PlanetVisualClass;
  volcanicLikelihood: number;
}

/**
 * A single ring system shape shared by every renderer that can show one. `bands` and `gapiness`
 * drive the procedural radial density pattern (see `createRingSystem` in planet-scene.ts) so a
 * ring never renders as one flat, uniformly transparent disc.
 */
export interface RingRecipe {
  /** Roughly how many density bands the radial noise pattern produces. */
  bands: number;
  color: Rgb;
  /** How pronounced the gaps between bands are, in [0, 1]. */
  gapiness: number;
  innerRadius: number;
  opacity: number;
  outerRadius: number;
}

interface BaseWorldRecipe {
  axialTilt: number;
  atmosphere: {
    color: Rgb;
    /** Overall optical thickness of the atmosphere shell, in [0, 1]. */
    density: number;
    /** Forward-scattered (Mie-like) haze strength around the light direction, in [0, 1]. */
    haze: number;
    label: string;
    /** Rayleigh-like scattering strength driving the limb/rim color shift, in [0, 1]. */
    scatterStrength: number;
  };
  classification: string;
  confidence: "low" | "medium" | "high";
  /** DERIVED physical properties this recipe was built from. */
  derived: PlanetDerivedProperties;
  /** INFERRED visual tendencies this recipe was built from — see PlanetInferredProperties. */
  inferred: PlanetInferredProperties;
  /** MEASURED catalog properties this recipe was built from, kept alongside the recipe so a
   * renderer or UI can show "why" a world looks the way it does without re-deriving it. */
  measured: PlanetMeasuredProperties;
  moon: {
    color: Rgb;
    inclination: number;
    orbitRadius: number;
    radius: number;
    speed: number;
  };
  radiusSceneUnits: number;
  rotationSpeed: number;
  seed: number;
  star: {
    apparentRadiusRadians: number;
    color: Rgb;
    intensity: number;
    radiusSceneUnits: number;
  };
  summary: string;
}

/**
 * GENERATED band-family parameters for a giant, exposed alongside (not instead of) the current
 * shader-facing `cloudBands` / `atmosphereBands` objects. These give a future renderer more
 * expressive room (band count, storm population, haze/atmosphere depth, a named palette family,
 * polar variation) without requiring a shader rewrite in this chunk.
 */
export interface GiantBandDetail {
  atmosphereDepth: number;
  bandContrast: number;
  bandCount: number;
  /** How crisply band edges resolve, in [0, 1] — low reads as smeared/diffuse, high as
   * distinctly striated. */
  bandSharpness: number;
  bandTurbulence: number;
  /** Strength of the domain-warp applied to band latitude before shading, in roughly [0, 1] —
   * the primary knob against mathematically perfect horizontal stripes. */
  bandWarp: number;
  haze: number;
  paletteFamily: GiantPaletteFamily;
  polarVariation: number;
  /** Per-storm hue-shift seed in [0, 1); combined with a storm's index to give each vortex a
   * slightly different tint instead of every storm reusing one identical color. */
  stormColorShift: number;
  stormCount: number;
  stormScale: number;
  stormStrength: number;
  /** Strength of the low-frequency latitude warp that makes band width vary with longitude
   * instead of every band holding one constant width, in roughly [0, 1]. */
  zonalVariation: number;
}

export interface GasGiantWorldRecipe extends BaseWorldRecipe {
  bandDetail: GiantBandDetail;
  cloudBands: {
    contrast: number;
    deepColor: Rgb;
    jetCount: number;
    lightColor: Rgb;
    midColor: Rgb;
    speed: number;
    stormColor: Rgb;
    stormLatitude: number;
    stormScale: number;
    stormStrength: number;
    turbulence: number;
  };
  renderer: "gas-giant";
  rings: RingRecipe | null;
}

export interface IceGiantWorldRecipe extends BaseWorldRecipe {
  atmosphereBands: {
    bandScale: number;
    deepColor: Rgb;
    hazeColor: Rgb;
    lightColor: Rgb;
    polarGlow: number;
    speed: number;
    stormLatitude: number;
    stormStrength: number;
  };
  bandDetail: GiantBandDetail;
  renderer: "ice-giant";
  rings: RingRecipe;
}

/**
 * GENERATED terrain parameters for a rocky world, exposed alongside (not instead of) the
 * current shader-facing `surface` object. These give a future renderer more expressive room
 * (continents, mountains, erosion, named palette family) without requiring a shader rewrite in
 * this chunk. Several fields intentionally mirror a `surface` field under the vocabulary this
 * chunk's spec asked for (e.g. `oceanCoverage` mirrors `surface.waterLevel`); they are kept in
 * sync by construction, not independently randomized.
 */
export interface RockyTerrainDetail {
  atmosphereDensity: number;
  cloudCoverage: number;
  continentalFragmentation: number;
  continentalScale: number;
  craterDensity: number;
  craterScale: number;
  erosionAmount: number;
  iceCoverage: number;
  lavaCoverage: number;
  mountainCoverage: number;
  mountainHeight: number;
  oceanCoverage: number;
  paletteFamily: RockyPaletteFamily;
  polarIceBias: number;
  terrainRoughness: number;
  volcanicActivity: number;
}

export interface RockyWorldRecipe extends BaseWorldRecipe {
  renderer: "rocky";
  /** Sparse debris/ice ring, distinct from the near-universal giant ring — most rocky worlds
   * have none. */
  rings: RingRecipe | null;
  surface: {
    cloudColor: Rgb;
    cloudCover: number;
    /** Radial noise scale for the cloud shell; higher reads as smaller, more numerous cells. */
    cloudScale: number;
    cloudSpeed: number;
    craterDensity: number;
    elevation: number;
    emissiveColor: Rgb;
    highColor: Rgb;
    iceCapStrength: number;
    lavaStrength: number;
    lowColor: Rgb;
    midColor: Rgb;
    roughness: number;
    waterColor: Rgb;
    /** Lighter, more scattered tint used near coastlines to distinguish shallow from deep water. */
    waterColorShallow: Rgb;
    waterLevel: number;
    /** Prevailing cloud-drift direction in radians, independent of the planet's own rotation. */
    windDirection: number;
  };
  terrain: RockyTerrainDetail;
}

export type WorldRecipe = GasGiantWorldRecipe | IceGiantWorldRecipe | RockyWorldRecipe;

export interface CustomPlanetParameters {
  activity: number;
  atmosphere: number;
  axialTilt: number;
  baseColor: Rgb;
  kind: Exclude<ExoplanetProfile["kind"], "unknown">;
  name: string;
  radius: number;
  rings: boolean;
  rotation: number;
  seed: number;
  temperatureKelvin: number;
  water: number;
}

export interface CustomWorld {
  planet: ExoplanetProfile;
  recipe: WorldRecipe;
}

export interface CustomStarParameters {
  activity: number;
  kind: StarKind;
  name: string;
  radius: number;
  rotation: number;
  seed: number;
  temperatureKelvin: number;
}

export interface CustomStar {
  star: StarProfile;
}

const hashString = (value: string): number => {
  let hash = 2166136261;

  for (const character of value) {
    hash ^= character.charCodeAt(0);
    hash = Math.imul(hash, 16777619);
  }

  return hash >>> 0;
};

/**
 * The single seed derivation used across every renderable object (catalog planets, catalog
 * stars, and their procedural counterparts). Folding in WORLDGEN_VERSION means a rule change
 * that intentionally alters recipes also changes every seed, so stale cached recipes never
 * get silently reused across versions. The identifier should be the most stable catalog key
 * available (NASA planet id, SIMBAD main identifier, or a procedural object's own id) so the
 * same astronomical object always maps to the same visual identity.
 */
export const hashObjectId = (id: string): number => hashString(`v${WORLDGEN_VERSION}:${id}`);

const createRandom = (seed: number): (() => number) => {
  let state = seed;

  return () => {
    state += 0x6d2b79f5;
    let value = state;
    value = Math.imul(value ^ (value >>> 15), value | 1);
    value ^= value + Math.imul(value ^ (value >>> 7), value | 61);
    return ((value ^ (value >>> 14)) >>> 0) / 4294967296;
  };
};

/** Clamps to [minimum, maximum], falling back to minimum for non-finite input so a bad or
 * missing upstream value (NaN, ±Infinity) can never leak into a shader uniform. */
const clamp = (value: number, minimum: number, maximum: number): number =>
  Number.isFinite(value) ? Math.min(maximum, Math.max(minimum, value)) : minimum;

/** Approximate a black-body color from NASA's stellar effective temperature. */
const temperatureToRgb = (temperatureKelvin: number): Rgb => {
  const temperature = clamp(temperatureKelvin, 1_000, 40_000) / 100;
  const red = temperature <= 66 ? 255 : 329.698727446 * (temperature - 60) ** -0.1332047592;
  const green =
    temperature <= 66
      ? 99.4708025861 * Math.log(temperature) - 161.1195681661
      : 288.1221695283 * (temperature - 60) ** -0.0755148492;
  const blue =
    temperature >= 66
      ? 255
      : temperature <= 19
        ? 0
        : 138.5177312231 * Math.log(temperature - 10) - 305.0447927307;

  return [clamp(red, 0, 255) / 255, clamp(green, 0, 255) / 255, clamp(blue, 0, 255) / 255];
};

/** Extracts the MEASURED catalog facts a planet's derived/inferred properties are built from,
 * kept separate so catalog data, math, and visual heuristics never get conflated. */
export const derivePlanetMeasuredProperties = (
  planet: ExoplanetProfile,
): PlanetMeasuredProperties => ({
  equilibriumTemperatureKelvin: planet.observation.equilibriumTemperatureKelvin,
  hostLuminosityLogSolar: planet.observation.hostLuminosityLogSolar,
  hostMassSolar: planet.observation.hostMassSolar,
  hostRadiusSolar: planet.observation.hostRadiusSolar,
  hostTemperatureKelvin: planet.observation.hostTemperatureKelvin,
  massEarth: planet.observation.massEarth,
  massJupiter: planet.observation.massJupiter,
  radiusEarth: planet.observation.radiusEarth,
  radiusJupiter: planet.observation.radiusJupiter,
  semiMajorAxisAu: planet.observation.semiMajorAxisAu,
});

/** Host-star luminosity in solar units, falling back to a mass-luminosity relation when SIMBAD
 * did not report it directly. Shared by deriveHostStar and derivePlanetDerivedProperties so the
 * two never silently disagree on what the host star's energy output is. */
const deriveHostLuminositySolar = (
  massSolar: number,
  hostLuminosityLogSolar: number | null,
): number =>
  clamp(
    hostLuminosityLogSolar === null ? massSolar ** 3.5 : 10 ** hostLuminosityLogSolar,
    1e-6,
    1e7,
  );

/** Combines MEASURED fields with established physics to obtain DERIVED properties. Every field
 * is `null` when an input it needs is missing, rather than being silently backfilled. */
export const derivePlanetDerivedProperties = (
  measured: PlanetMeasuredProperties,
): PlanetDerivedProperties => {
  const radiusEarthEffective =
    measured.radiusEarth ?? (measured.radiusJupiter !== null ? measured.radiusJupiter * 11.209 : 1);
  const massEarthEffective =
    measured.massEarth ?? (measured.massJupiter !== null ? measured.massJupiter * 317.83 : 1);

  // Earth's mean density (5.51 g/cm^3) scaled by mass/radius^3 relative to Earth; only computed
  // when both the mass and radius came directly from the catalog, so a fallback-filled radius
  // (e.g. defaulted to 1 Earth radius) can never masquerade as a measured density.
  const bulkDensityGCm3 =
    measured.massEarth !== null && measured.radiusEarth !== null && measured.radiusEarth > 0
      ? clamp((5.51 * measured.massEarth) / measured.radiusEarth ** 3, 0, 200)
      : null;

  const massSolar = clamp(measured.hostMassSolar ?? 1, 0.08, 150);
  const luminositySolar = deriveHostLuminositySolar(massSolar, measured.hostLuminosityLogSolar);
  const insolationEarthRelative =
    measured.hostLuminosityLogSolar !== null &&
    measured.semiMajorAxisAu !== null &&
    measured.semiMajorAxisAu > 0
      ? clamp(luminositySolar / measured.semiMajorAxisAu ** 2, 1e-6, 1e9)
      : null;

  return {
    bulkDensityGCm3,
    insolationEarthRelative,
    massEarthEffective: clamp(massEarthEffective, 1e-3, 1e6),
    radiusEarthEffective: clamp(radiusEarthEffective, 1e-2, 200),
  };
};

/** How many independent physical properties actually backed an inference — used only to grade
 * `confidence`, never to change the inference itself. */
const countKnownInputs = (values: readonly (number | null)[]): number =>
  values.filter((value) => value !== null).length;

/** Builds a cautious, probabilistic INFERRED read on a planet's likely appearance from its
 * MEASURED and DERIVED properties. Rocky-kind objects are further split into rocky /
 * ocean_candidate / ice / lava / unknown; giant-kind objects are split into gas_giant /
 * hot_gas_giant / ice_giant. Deliberately conservative: an object with no known temperature or
 * density stays "unknown" rather than being assigned a confident-looking guess. */
export const derivePlanetInferredProperties = (
  planet: ExoplanetProfile,
  measured: PlanetMeasuredProperties,
  derived: PlanetDerivedProperties,
  random: () => number,
): PlanetInferredProperties => {
  const temperature = measured.equilibriumTemperatureKelvin;
  const density = derived.bulkDensityGCm3;
  const knownInputs = countKnownInputs([
    temperature,
    density,
    derived.insolationEarthRelative,
    measured.radiusEarth ?? measured.radiusJupiter,
  ]);
  const confidence: PlanetInferredProperties["confidence"] =
    knownInputs >= 3 ? "high" : knownInputs >= 1 ? "medium" : "low";

  if (planet.kind === "gas-giant" || planet.kind === "ice-giant") {
    const isUltraHot = temperature !== null && temperature >= 1_800;
    const isHot = temperature !== null && temperature >= 1_000;
    const isCold = temperature !== null && temperature > 0 && temperature < 220;
    const visualClass: PlanetVisualClass =
      planet.kind === "ice-giant" ? "ice_giant" : isHot ? "hot_gas_giant" : "gas_giant";
    // Temperature buckets the same way the renderer's own thermal thresholds do, but always
    // leaves a deterministic random() draw between the plausible families for that bucket so a
    // giant never looks identical to every other giant sharing its temperature range.
    const paletteFamily: GiantPaletteFamily =
      planet.kind === "ice-giant"
        ? isHot
          ? "methane-blue"
          : random() > 0.5
            ? "methane-blue"
            : "cyan-ice"
        : isUltraHot
          ? "ultrahot-red-brown"
          : isHot
            ? "hot-dark-red"
            : isCold
              ? random() > 0.5
                ? "pale-gold"
                : "neutral-cloud"
              : random() > 0.5
                ? "cream-brown"
                : "pale-gold";

    return {
      confidence,
      // Low irradiation is required for any surface ice; a giant's own volatile-rich envelope
      // is the basis for this, not a claim about a literal solid surface.
      iceLikelihood: temperature === null ? 0.3 : clampUnit(1 - temperature / 900),
      oceanLikelihood: 0,
      paletteFamily,
      visualClass,
      volcanicLikelihood: 0,
    };
  }

  // Reduce plausible surface ice as equilibrium temperature climbs, and increase hot/lava
  // tendency under very high irradiation, per the chunk's inference rules — but only when the
  // relevant catalog field is actually known.
  const iceLikelihood = temperature === null ? 0.4 : clampUnit(1 - (temperature - 150) / 250);
  const volcanicFromTemperature = temperature === null ? 0 : clampUnit((temperature - 500) / 700);
  const volcanicFromInsolation =
    derived.insolationEarthRelative === null
      ? 0
      : clampUnit((derived.insolationEarthRelative - 4) / 40);
  const volcanicLikelihood = Math.max(volcanicFromTemperature, volcanicFromInsolation);
  // A bulk density well below rock (~3-8 g/cm^3) suggests a volatile-rich (likely water-rich)
  // composition rather than bare silicate; combined with a temperate equilibrium temperature
  // this raises ocean likelihood.
  const isTemperate = temperature !== null && temperature >= 180 && temperature <= 330;
  const oceanLikelihood =
    isTemperate && density !== null ? clampUnit(1 - (density - 1) / 4) : isTemperate ? 0.3 : 0;

  let visualClass: PlanetVisualClass = "unknown";
  if (temperature !== null) {
    if (volcanicLikelihood > 0.5) visualClass = "lava";
    else if (iceLikelihood > 0.6) visualClass = "ice";
    else if (oceanLikelihood > 0.55) visualClass = "ocean_candidate";
    else visualClass = "rocky";
  }

  const paletteFamily: RockyPaletteFamily =
    visualClass === "lava"
      ? "lava-black-red"
      : visualClass === "ice"
        ? "ice-blue"
        : density !== null && density >= 7
          ? "iron-rich"
          : density !== null && density > 0 && density <= 3.5
            ? random() > 0.5
              ? "carbon-dark"
              : "basaltic-dark"
            : (
                [
                  "oxidized-red",
                  "silicate-neutral",
                  "basaltic-dark",
                  "sulfuric-yellow",
                  "desert-tan",
                ] as const
              )[Math.floor(random() * 5)];

  return {
    confidence,
    iceLikelihood,
    oceanLikelihood,
    paletteFamily,
    visualClass,
    volcanicLikelihood,
  };
};

export const deriveHostStar = (planet: ExoplanetProfile): BaseWorldRecipe["star"] => {
  // Clamped to plausible stellar ranges before any pow/log/division so a corrupt or
  // out-of-range catalog value (or an Infinity produced by a prior fallback) can never
  // divide Infinity by Infinity into a NaN that would otherwise reach the shader.
  const massSolar = clamp(planet.observation.hostMassSolar ?? 1, 0.08, 150);
  const radiusSolar = clamp(planet.observation.hostRadiusSolar ?? massSolar ** 0.8, 0.08, 2_000);
  const luminositySolar = deriveHostLuminositySolar(
    massSolar,
    planet.observation.hostLuminosityLogSolar,
  );
  const temperatureKelvin = clamp(
    planet.observation.hostTemperatureKelvin ??
      5_772 * (luminositySolar / radiusSolar ** 2) ** 0.25,
    500,
    200_000,
  );
  const orbitalDistanceAu = planet.observation.semiMajorAxisAu;
  const physicalAngularRadius =
    orbitalDistanceAu !== null && orbitalDistanceAu > 0
      ? Math.asin(clamp((radiusSolar * 0.00465047) / orbitalDistanceAu, 0, 0.95))
      : 0.00465047 * Math.sqrt(radiusSolar);

  return {
    color: temperatureToRgb(temperatureKelvin),
    radiusSceneUnits: clamp(1.5 + Math.log2(radiusSolar + 0.5) * 1.1, 1.1, 5.5),
    intensity: clamp(1.45 + Math.log10(Math.max(0.001, luminositySolar)) * 0.34, 0.65, 3.2),
    // Preserve the relative apparent sizes while keeping ordinary stars legible in the terrain sky.
    apparentRadiusRadians: clamp(physicalAngularRadius * 2.4, 0.012, 0.09),
  };
};

interface GasGiantPalette {
  atmosphere: Rgb;
  deepColor: Rgb;
  lightColor: Rgb;
  midColor: Rgb;
  stormColor: Rgb;
}

/**
 * Single source of truth for gas-giant surface color, keyed by the same GiantPaletteFamily
 * `derivePlanetInferredProperties` assigns — so `bandDetail.paletteFamily` (a named family) and
 * the literal RGBs the shader actually renders can never drift apart. Every family reads
 * distinctly from Jupiter's cream/brown so "don't copy Jupiter's colors for every giant" holds.
 */
const GAS_GIANT_PALETTES: Record<GiantPaletteFamily, GasGiantPalette> = {
  "cream-brown": {
    deepColor: [0.07, 0.1, 0.16],
    midColor: [0.46, 0.32, 0.2],
    lightColor: [0.93, 0.8, 0.54],
    atmosphere: [0.38, 0.66, 1],
    stormColor: [0.92, 0.7, 0.42],
  },
  // Saturn-like: paler and lower-contrast than cream-brown rather than a hue swap.
  "pale-gold": {
    deepColor: [0.14, 0.13, 0.09],
    midColor: [0.62, 0.53, 0.34],
    lightColor: [0.97, 0.9, 0.72],
    atmosphere: [0.55, 0.68, 0.85],
    stormColor: [0.98, 0.86, 0.6],
  },
  "methane-blue": {
    deepColor: [0.03, 0.08, 0.14],
    midColor: [0.13, 0.36, 0.5],
    lightColor: [0.55, 0.82, 0.86],
    atmosphere: [0.2, 0.6, 0.92],
    stormColor: [0.72, 0.92, 0.9],
  },
  "cyan-ice": {
    deepColor: [0.025, 0.045, 0.09],
    midColor: [0.2, 0.31, 0.45],
    lightColor: [0.68, 0.78, 0.83],
    atmosphere: [0.28, 0.56, 0.9],
    stormColor: [0.68, 0.84, 0.95],
  },
  "hot-dark-red": {
    deepColor: [0.16, 0.025, 0.025],
    midColor: [0.78, 0.2, 0.07],
    lightColor: [1, 0.68, 0.28],
    atmosphere: [1, 0.28, 0.08],
    stormColor: [1, 0.58, 0.24],
  },
  "ultrahot-red-brown": {
    deepColor: [0.075, 0.008, 0.025],
    midColor: [0.62, 0.055, 0.075],
    lightColor: [1, 0.82, 0.42],
    atmosphere: [1, 0.16, 0.12],
    stormColor: [1, 0.5, 0.16],
  },
  "neutral-cloud": {
    deepColor: [0.09, 0.09, 0.1],
    midColor: [0.44, 0.43, 0.42],
    lightColor: [0.86, 0.85, 0.82],
    atmosphere: [0.5, 0.54, 0.6],
    stormColor: [0.9, 0.88, 0.8],
  },
};

interface IceGiantPalette {
  atmosphere: Rgb;
  deepColor: Rgb;
  hazeColor: Rgb;
  lightColor: Rgb;
}

/** Mirrors GAS_GIANT_PALETTES for ice giants. Only cyan-ice/methane-blue/neutral-cloud are ever
 * assigned by derivePlanetInferredProperties for ice-giant kind objects; the remaining families
 * are filled in for type completeness and to keep a custom-built world well-defined regardless
 * of which family it inherits. */
const ICE_GIANT_PALETTES: Record<GiantPaletteFamily, IceGiantPalette> = {
  "cyan-ice": {
    deepColor: [0.018, 0.055, 0.2],
    hazeColor: [0.09, 0.28, 0.68],
    lightColor: [0.42, 0.68, 1],
    atmosphere: [0.16, 0.48, 1],
  },
  "methane-blue": {
    deepColor: [0.025, 0.17, 0.25],
    hazeColor: [0.08, 0.54, 0.64],
    lightColor: [0.48, 0.88, 0.86],
    atmosphere: [0.16, 0.82, 0.92],
  },
  "neutral-cloud": {
    deepColor: [0.05, 0.07, 0.09],
    hazeColor: [0.32, 0.36, 0.4],
    lightColor: [0.78, 0.82, 0.85],
    atmosphere: [0.4, 0.48, 0.58],
  },
  "cream-brown": {
    deepColor: [0.05, 0.06, 0.08],
    hazeColor: [0.3, 0.26, 0.2],
    lightColor: [0.8, 0.74, 0.6],
    atmosphere: [0.42, 0.5, 0.62],
  },
  "pale-gold": {
    deepColor: [0.06, 0.06, 0.05],
    hazeColor: [0.4, 0.36, 0.24],
    lightColor: [0.88, 0.82, 0.66],
    atmosphere: [0.5, 0.56, 0.66],
  },
  "hot-dark-red": {
    deepColor: [0.1, 0.02, 0.02],
    hazeColor: [0.4, 0.12, 0.08],
    lightColor: [0.85, 0.5, 0.28],
    atmosphere: [0.7, 0.24, 0.14],
  },
  "ultrahot-red-brown": {
    deepColor: [0.06, 0.01, 0.02],
    hazeColor: [0.35, 0.06, 0.06],
    lightColor: [0.85, 0.62, 0.34],
    atmosphere: [0.75, 0.15, 0.1],
  },
};

const deriveGasGiantRecipe = (
  planet: ExoplanetProfile,
  seed: number,
  random: () => number,
): GasGiantWorldRecipe => {
  const measured = derivePlanetMeasuredProperties(planet);
  const derived = derivePlanetDerivedProperties(measured);
  const inferred = derivePlanetInferredProperties(planet, measured, derived, random);
  const equilibriumTemperature = planet.observation.equilibriumTemperatureKelvin ?? 0;
  const radiusJupiter =
    planet.observation.radiusJupiter ??
    (planet.observation.radiusEarth !== null ? planet.observation.radiusEarth / 11.209 : 1);
  const massJupiter = planet.observation.massJupiter ?? 0;
  const isUltraHot = equilibriumTemperature >= 1_800;
  const isHot = equilibriumTemperature >= 1_000;
  const isCold = equilibriumTemperature > 0 && equilibriumTemperature < 220;
  // `inferred.paletteFamily` is typed as GiantPaletteFamily | RockyPaletteFamily because
  // derivePlanetInferredProperties also serves rocky worlds; an object with an "unknown"
  // catalog kind (which deriveWorldRecipe falls back to rendering as a gas giant) can reach
  // here carrying a RockyPaletteFamily value, so the lookup falls back to a default family
  // instead of indexing the giant palette table with a key it does not contain.
  const palette =
    GAS_GIANT_PALETTES[inferred.paletteFamily as GiantPaletteFamily] ??
    GAS_GIANT_PALETTES["cream-brown"];
  const scaledRadius = 3.8 + Math.min(radiusJupiter, 2) * 0.45;
  const hasProminentRings = random() > 0.62;
  const stormHue = random();
  const bandTurbulence = 1.8 + random() * 1.4;
  const bandContrast = 0.62 + random() * 0.16;
  const bandSharpness = 0.32 + random() * 0.44;
  const bandWarp = 0.55 + random() * 0.85;
  const zonalVariation = 0.15 + random() * 0.4;
  const jetCount = 13 + Math.floor(random() * 12);
  const stormStrength = 0.32 + random() * 0.58;
  const stormScale = 3.2 + random() * 3.8;
  // Blending a palette-native storm accent toward that same palette's light color, by a
  // per-planet hue draw, keeps every storm on a giant recognizably part of its family instead of
  // reading as an arbitrary color pasted on top.
  const stormColor = mixColor(palette.stormColor, palette.lightColor, stormHue * 0.4);

  return {
    seed,
    measured,
    derived,
    inferred,
    star: deriveHostStar(planet),
    renderer: "gas-giant",
    classification: isUltraHot
      ? "Ultra-hot Jupiter"
      : isHot && massJupiter >= 5
        ? "Young super-Jupiter"
        : isHot
          ? "Hot Jupiter"
          : isCold
            ? "Cold gas giant"
            : "Gas giant",
    confidence: inferred.confidence,
    radiusSceneUnits: scaledRadius,
    rotationSpeed: 0.022 + random() * 0.01,
    axialTilt: -0.16 + random() * 0.32,
    bandDetail: {
      paletteFamily: inferred.paletteFamily as GiantPaletteFamily,
      bandCount: jetCount,
      bandContrast,
      bandSharpness,
      bandTurbulence,
      bandWarp,
      zonalVariation,
      stormCount: 1 + Math.floor(random() * 3),
      stormScale,
      stormStrength,
      stormColorShift: stormHue,
      haze: clampUnit(0.15 + inferred.iceLikelihood * 0.35),
      atmosphereDepth: 0.55 + random() * 0.35,
      polarVariation: 0.1 + random() * 0.3,
    },
    cloudBands: {
      deepColor: palette.deepColor,
      midColor: palette.midColor,
      lightColor: palette.lightColor,
      speed: 0.022 + random() * 0.018,
      turbulence: bandTurbulence,
      contrast: bandContrast,
      jetCount,
      stormLatitude: -0.48 + random() * 0.96,
      stormScale,
      stormStrength,
      stormColor,
    },
    atmosphere: {
      color: palette.atmosphere,
      density: 0.7 + random() * 0.25,
      haze: clampUnit(0.15 + inferred.iceLikelihood * 0.35),
      label: "Hydrogen / helium · inferred",
      scatterStrength: 0.5 + random() * 0.3,
    },
    moon: {
      radius: scaledRadius * (0.075 + random() * 0.025),
      orbitRadius: scaledRadius * (1.7 + random() * 0.2),
      speed: 0.055 + random() * 0.02,
      inclination: -0.22 + random() * 0.44,
      color: isHot ? [0.29, 0.19, 0.14] : [0.22, 0.25, 0.29],
    },
    rings: hasProminentRings
      ? {
          bands: 4 + Math.floor(random() * 6),
          color: isHot ? [0.66, 0.35, 0.19] : [0.42, 0.52, 0.62],
          gapiness: 0.3 + random() * 0.5,
          innerRadius: scaledRadius * (1.22 + random() * 0.12),
          opacity: 0.12 + random() * 0.12,
          outerRadius: scaledRadius * (1.42 + random() * 0.24),
        }
      : null,
    summary: hasProminentRings
      ? "A giant world with animated jet bands, a long-lived storm vortex, and a sparse ring system inferred from its measured scale and thermal regime."
      : "A giant world with animated jet bands and a long-lived storm vortex, colored by its measured scale and thermal regime.",
  };
};

const deriveRockyRecipe = (
  planet: ExoplanetProfile,
  seed: number,
  random: () => number,
): RockyWorldRecipe => {
  const measured = derivePlanetMeasuredProperties(planet);
  const derived = derivePlanetDerivedProperties(measured);
  const inferred = derivePlanetInferredProperties(planet, measured, derived, random);
  const temperature = planet.observation.equilibriumTemperatureKelvin;
  const radiusEarth = planet.observation.radiusEarth ?? 1;
  const scaledRadius = 3.25 + Math.min(Math.max(radiusEarth, 0.3), 2) * 0.34;
  const isScorched = temperature !== null && temperature > 500;
  const isTemperate = temperature !== null && temperature >= 180 && temperature <= 330;
  const isFrozen = temperature !== null && temperature < 180;
  // Deep-frozen worlds (below roughly the CO2 frost line) glaciate edge to edge rather than
  // just at the poles.
  const isGlobalIce = temperature !== null && temperature < 120;
  const isOceanCandidate = inferred.visualClass === "ocean_candidate";
  // An ocean-candidate world that is also frozen reads as an ice-locked ocean (Europa-like)
  // rather than a dry, waterless world.
  const isFrozenOcean = isFrozen && isOceanCandidate;
  const paletteFamily = inferred.paletteFamily as RockyPaletteFamily;

  // Liquid chemistry is not always Earth-blue water: tint the ocean by inferred surface
  // chemistry (a sulfuric world reads as a murky, reactive sea; an oxidized world as a rusty
  // brine; an iron-rich world as a dark, metallic melt) rather than assuming one universal color.
  const temperateWaterColor: Rgb =
    paletteFamily === "sulfuric-yellow"
      ? [0.14, 0.16, 0.03]
      : paletteFamily === "oxidized-red"
        ? [0.1, 0.05, 0.02]
        : paletteFamily === "iron-rich"
          ? [0.01, 0.05, 0.05]
          : paletteFamily === "carbon-dark"
            ? [0.012, 0.02, 0.03]
            : [0.015, 0.13, 0.24];

  const palette = isScorched
    ? {
        lowColor: [0.12, 0.025, 0.012] as const,
        midColor: [0.52, 0.12, 0.035] as const,
        highColor: [0.93, 0.47, 0.13] as const,
        waterColor: [0.2, 0.035, 0.018] as const,
        atmosphere: [1, 0.28, 0.08] as const,
      }
    : isFrozen
      ? {
          lowColor: [0.055, 0.095, 0.13] as const,
          midColor: [0.36, 0.5, 0.57] as const,
          highColor: [0.83, 0.92, 0.94] as const,
          waterColor: isFrozenOcean
            ? mixColor(temperateWaterColor, [0.83, 0.92, 0.94], 0.5)
            : ([0.025, 0.09, 0.15] as Rgb),
          atmosphere: [0.35, 0.7, 1] as const,
        }
      : isTemperate
        ? {
            lowColor: [0.08, 0.16, 0.07] as const,
            midColor: [0.38, 0.3, 0.16] as const,
            highColor: [0.72, 0.67, 0.54] as const,
            waterColor: temperateWaterColor,
            atmosphere: [0.22, 0.62, 1] as const,
          }
        : {
            lowColor: [0.09, 0.075, 0.07] as const,
            midColor: [0.34, 0.26, 0.2] as const,
            highColor: [0.67, 0.58, 0.48] as const,
            waterColor: [0.035, 0.06, 0.075] as const,
            atmosphere: [0.42, 0.5, 0.58] as const,
          };

  const classification = isScorched
    ? "Scorched rocky world"
    : isFrozenOcean
      ? "Ice-locked ocean world"
      : isGlobalIce
        ? "Glaciated rocky world"
        : isFrozen
          ? "Frozen rocky world"
          : isOceanCandidate
            ? "Ocean-candidate world"
            : isTemperate
              ? "Temperate rocky world"
              : "Rocky world";

  const elevation = 0.13 + random() * 0.12;
  const roughness = 2.1 + random() * 1.4;
  const craterDensity = 0.38 + random() * 0.34;
  const waterLevel = isTemperate
    ? 0.4 + random() * 0.08
    : isFrozenOcean
      ? 0.36 + random() * 0.1
      : 0;
  const lavaStrength = isScorched ? 0.5 + random() * 0.42 : 0;
  const iceCapStrength = isGlobalIce
    ? 0.94 + random() * 0.05
    : isFrozen
      ? 0.78 + random() * 0.18
      : isTemperate
        ? 0.28 + random() * 0.2
        : 0;
  const cloudCover = isTemperate ? 0.3 + random() * 0.34 : isFrozen ? 0.12 + random() * 0.16 : 0;
  const hasDebrisRing = random() > 0.86;

  return {
    seed,
    measured,
    derived,
    inferred,
    star: deriveHostStar(planet),
    renderer: "rocky",
    classification,
    confidence: inferred.confidence,
    radiusSceneUnits: scaledRadius,
    rotationSpeed: 0.014 + random() * 0.012,
    axialTilt: -0.34 + random() * 0.68,
    atmosphere: {
      color: palette.atmosphere,
      density: isTemperate
        ? 0.5 + random() * 0.4
        : isScorched
          ? 0.15 + random() * 0.25
          : 0.2 + random() * 0.3,
      haze: clampUnit(0.12 + cloudCover * 0.4),
      label: isScorched
        ? "Mineral vapor · inferred"
        : isTemperate
          ? "Secondary atmosphere · inferred"
          : "Thin volatiles · inferred",
      scatterStrength: isTemperate ? 0.55 + random() * 0.3 : 0.3 + random() * 0.3,
    },
    rings: hasDebrisRing
      ? {
          bands: 3 + Math.floor(random() * 4),
          color: isFrozen ? [0.75, 0.82, 0.88] : [0.55, 0.5, 0.46],
          gapiness: 0.3 + random() * 0.4,
          innerRadius: scaledRadius * (1.3 + random() * 0.1),
          opacity: 0.05 + random() * 0.08,
          outerRadius: scaledRadius * (1.7 + random() * 0.5),
        }
      : null,
    surface: {
      ...palette,
      elevation,
      roughness,
      craterDensity,
      waterLevel,
      waterColorShallow: mixColor(palette.waterColor, palette.highColor, 0.4),
      lavaStrength,
      emissiveColor: isScorched ? [1, 0.16, 0.015] : [0, 0, 0],
      iceCapStrength,
      cloudCover,
      cloudScale: 2.2 + random() * 2.4,
      cloudSpeed: 0.016 + random() * 0.016,
      cloudColor: isFrozen ? [0.58, 0.75, 0.86] : [0.84, 0.9, 0.94],
      windDirection: random() * Math.PI * 2,
    },
    terrain: {
      paletteFamily: inferred.paletteFamily as RockyPaletteFamily,
      oceanCoverage: waterLevel,
      continentalScale: 0.4 + random() * 0.5,
      continentalFragmentation: 0.2 + random() * 0.6,
      mountainCoverage: 0.15 + roughness * 0.08,
      mountainHeight: elevation,
      terrainRoughness: clampUnit(roughness / 3.5),
      erosionAmount: isTemperate ? 0.3 + random() * 0.4 : 0.05 + random() * 0.25,
      craterDensity,
      craterScale: 0.5 + random() * 1.5,
      iceCoverage: iceCapStrength,
      polarIceBias: isGlobalIce
        ? 0.85 + random() * 0.15
        : isFrozen
          ? 0.55 + random() * 0.4
          : isTemperate
            ? 0.15 + random() * 0.2
            : 0,
      volcanicActivity: lavaStrength,
      lavaCoverage: isScorched ? 0.2 + random() * 0.5 : 0,
      cloudCoverage: cloudCover,
      atmosphereDensity: isTemperate
        ? 0.5 + random() * 0.4
        : isScorched
          ? 0.15 + random() * 0.25
          : 0.2 + random() * 0.3,
    },
    moon: {
      radius: scaledRadius * (0.055 + random() * 0.025),
      orbitRadius: scaledRadius * (1.72 + random() * 0.22),
      speed: 0.045 + random() * 0.024,
      inclination: -0.34 + random() * 0.68,
      color: isFrozen ? [0.32, 0.38, 0.42] : [0.24, 0.22, 0.2],
    },
    summary: isScorched
      ? "An intensely heated mineral world with glowing fracture networks, dark impact basins, and a thin vapor haze generated from its measured thermal regime."
      : isOceanCandidate
        ? "A speculative ocean-candidate world with broad water coverage, drifting cloud systems, and scattered highland terrain, inferred from its low bulk density and temperate equilibrium temperature."
        : isTemperate
          ? "A speculative temperate world with ocean basins, drifting cloud systems, highland terrain, and polar ice generated from its measured scale and temperature."
          : isFrozen
            ? "A frozen rocky world with broad polar ice, weathered highlands, impact basins, and sparse drifting cloud systems."
            : "A rocky world with weathered highlands and impact basins, generated with limited scale and temperature data.",
  };
};

const deriveIceGiantRecipe = (
  planet: ExoplanetProfile,
  seed: number,
  random: () => number,
): IceGiantWorldRecipe => {
  const measured = derivePlanetMeasuredProperties(planet);
  const derived = derivePlanetDerivedProperties(measured);
  const inferred = derivePlanetInferredProperties(planet, measured, derived, random);
  const temperature = planet.observation.equilibriumTemperatureKelvin;
  const radiusEarth = planet.observation.radiusEarth ?? 4;
  const scaledRadius = 3.55 + Math.min(Math.max(radiusEarth, 2), 6) * 0.11;
  const isWarm = temperature !== null && temperature >= 700;
  // See the matching comment in deriveGasGiantRecipe: falls back to a default family when the
  // inferred palette family came from the rocky-world inference branch instead of the giant one.
  const palette =
    ICE_GIANT_PALETTES[inferred.paletteFamily as GiantPaletteFamily] ??
    ICE_GIANT_PALETTES["cyan-ice"];
  const bandScale = 9 + random() * 5;
  const bandStormStrength = 0.32 + random() * 0.28;
  const polarGlow = 0.2 + random() * 0.46;
  const bandSharpness = 0.16 + random() * 0.3;
  const bandWarp = 0.35 + random() * 0.5;
  const zonalVariation = 0.18 + random() * 0.32;
  const stormColorShift = random();

  return {
    seed,
    measured,
    derived,
    inferred,
    star: deriveHostStar(planet),
    renderer: "ice-giant",
    classification: isWarm ? "Warm Neptune" : "Ice giant",
    confidence: inferred.confidence,
    radiusSceneUnits: scaledRadius,
    rotationSpeed: 0.024 + random() * 0.016,
    axialTilt: -0.46 + random() * 0.92,
    atmosphere: {
      color: palette.atmosphere,
      density: 0.6 + random() * 0.3,
      haze: clampUnit(0.35 + inferred.iceLikelihood * 0.3),
      label: "Hydrogen / helium / methane · inferred",
      scatterStrength: 0.45 + random() * 0.3,
    },
    bandDetail: {
      paletteFamily: inferred.paletteFamily as GiantPaletteFamily,
      bandCount: 6 + Math.floor(random() * 6),
      bandContrast: 0.4 + random() * 0.3,
      bandSharpness,
      bandTurbulence: 0.8 + random() * 0.8,
      bandWarp,
      zonalVariation,
      stormCount: 1 + Math.floor(random() * 2),
      stormScale: 2 + random() * 3,
      stormStrength: bandStormStrength,
      stormColorShift,
      haze: clampUnit(0.35 + inferred.iceLikelihood * 0.3),
      atmosphereDepth: 0.6 + random() * 0.3,
      polarVariation: polarGlow,
    },
    atmosphereBands: {
      ...palette,
      speed: 0.018 + random() * 0.015,
      bandScale,
      stormStrength: bandStormStrength,
      stormLatitude: -0.5 + random(),
      polarGlow,
    },
    rings: {
      bands: 3 + Math.floor(random() * 5),
      color: isWarm ? [0.28, 0.55, 0.58] : [0.3, 0.45, 0.72],
      gapiness: 0.25 + random() * 0.45,
      innerRadius: scaledRadius * (1.16 + random() * 0.1),
      opacity: 0.1 + random() * 0.12,
      outerRadius: scaledRadius * (1.35 + random() * 0.12),
    },
    moon: {
      radius: scaledRadius * (0.045 + random() * 0.025),
      orbitRadius: scaledRadius * (1.7 + random() * 0.24),
      speed: 0.04 + random() * 0.025,
      inclination: -0.42 + random() * 0.84,
      color: isWarm ? [0.2, 0.29, 0.3] : [0.2, 0.24, 0.32],
    },
    summary:
      "A deep volatile-rich atmosphere rendered with methane-tinted haze, subdued cloud bands, and a faint debris ring inferred from its measured scale and temperature.",
  };
};

export const deriveWorldRecipe = (planet: ExoplanetProfile): WorldRecipe => {
  const seed = hashObjectId(planet.id);
  const random = createRandom(seed);

  if (planet.kind === "rocky") return deriveRockyRecipe(planet, seed, random);
  if (planet.kind === "ice-giant") return deriveIceGiantRecipe(planet, seed, random);
  return deriveGasGiantRecipe(planet, seed, random);
};

const clampUnit = (value: number): number =>
  Number.isFinite(value) ? Math.min(1, Math.max(0, value)) : 0;

const temperatureToSpectralClass = (temperatureKelvin: number): string => {
  if (temperatureKelvin >= 30_000) return "O";
  if (temperatureKelvin >= 10_000) return "B";
  if (temperatureKelvin >= 7_500) return "A";
  if (temperatureKelvin >= 6_000) return "F";
  if (temperatureKelvin >= 5_200) return "G";
  if (temperatureKelvin >= 3_700) return "K";
  return "M";
};

const luminosityClass = (kind: StarKind): string => {
  if (kind === "white-dwarf") return "D";
  if (kind === "neutron-star") return "NS";
  if (kind === "evolved") return "III";
  return "V";
};

const starKindDescription: Record<StarKind, string> = {
  binary: "Custom binary star",
  evolved: "Custom giant star",
  "main-sequence": "Custom main-sequence star",
  "neutron-star": "Custom neutron star",
  star: "Custom star",
  variable: "Custom variable star",
  "white-dwarf": "Custom white dwarf",
};

/** Catalog facts about a star, normalized from SIMBAD (or a custom generator) and free of any
 * rendering assumptions. */
export interface StarPhysicalProperties {
  effectiveTemperatureKelvin: number | null;
  spectralType: string | null;
}

/** Renderer-facing parameters derived from a star's physical properties. Every field here is a
 * visualization assumption, not a catalog fact — see StarPhysicalProperties for the source data.
 * `activity` and `rotationFactor` come straight from a custom generator's inputs when present;
 * the remaining GENERATED fields (spotCoverage, granulation, coronalIntensity) are deterministic
 * tendencies driven by activity and spectral class, not observations. */
export interface StarVisualRecipe {
  activity: number;
  color: Rgb;
  coronalIntensity: number;
  granulationScale: number;
  granulationStrength: number;
  label: string;
  radiusSceneUnits: number;
  rotationFactor: number;
  seed: number;
  spectralClassification: string;
  spotCoverage: number;
  temperatureKelvin: number;
}

/** Fallback temperatures/labels by spectral letter when no measured temperature is available.
 * Color is never stored here — it's always derived from temperatureToRgb so a star's displayed
 * hue is a single physically-motivated blackbody curve rather than hand-picked cartoon spectral
 * colors (a G star should read as warm white, not saturated banana yellow). */
const spectralStarPalette: Record<string, { label: string; temperatureKelvin: number }> = {
  O: { temperatureKelvin: 35_000, label: "Blue star" },
  B: { temperatureKelvin: 18_000, label: "Blue-white star" },
  A: { temperatureKelvin: 8_500, label: "White star" },
  F: { temperatureKelvin: 6_700, label: "White star" },
  G: { temperatureKelvin: 5_700, label: "Yellow star" },
  K: { temperatureKelvin: 4_500, label: "Orange star" },
  M: { temperatureKelvin: 3_200, label: "Red star" },
};

/** Extracts the physical facts a star's visual recipe is derived from, kept separate so the
 * catalog data and the rendering assumptions built on top of it never get conflated. */
export const deriveStarPhysicalProperties = (star: StarProfile): StarPhysicalProperties => ({
  effectiveTemperatureKelvin: star.customization?.temperatureKelvin ?? null,
  spectralType: star.observation.spectralType,
});

/**
 * Derives a stable visual recipe for a star, mirroring deriveWorldRecipe for planets. The seed
 * is hashed from the star's own catalog id (its SIMBAD-derived identifier, or the embedded seed
 * of a procedural star), so the same star always resolves to the same visual identity.
 */
export const deriveStarRecipe = (star: StarProfile): StarVisualRecipe => {
  const seed = hashObjectId(star.id);
  const random = createRandom(seed);
  const physical = deriveStarPhysicalProperties(star);
  const spectralClass = physical.spectralType?.match(/[OBAFGKM]/i)?.[0]?.toUpperCase();
  const palette = spectralStarPalette[spectralClass ?? "G"] ?? spectralStarPalette.G;
  const temperatureKelvin =
    physical.effectiveTemperatureKelvin === null
      ? palette.temperatureKelvin
      : clamp(physical.effectiveTemperatureKelvin, 1_000, 40_000);
  // Always the same blackbody curve, whether the temperature came from a measurement or a
  // spectral-class fallback, so color and temperatureKelvin never disagree with each other.
  const color = temperatureToRgb(temperatureKelvin);
  const activity = clampUnit(star.customization?.activity ?? 0.55);
  // Cooler stars carry deeper convective envelopes and tend toward more, larger granules;
  // hotter stars run more radiative and show comparatively little granulation. This is a
  // generic stellar-physics tendency, not a per-star measurement.
  const convectiveTendency = clampUnit(1 - (temperatureKelvin - 3_000) / 27_000);

  return {
    seed,
    temperatureKelvin,
    color,
    label: palette.label,
    radiusSceneUnits: 5.6 + clampUnit(star.customization?.radius ?? 0.5) * 3.2,
    activity,
    spectralClassification: `${spectralClass ?? "G"}${luminosityClass(star.kind)}`,
    rotationFactor: clampUnit(star.customization?.rotation ?? 0.5),
    spotCoverage: clampUnit(activity * (0.15 + random() * 0.35)),
    granulationScale: 0.4 + convectiveTendency * 1.6 + random() * 0.3,
    granulationStrength: clampUnit(0.2 + convectiveTendency * 0.5 + random() * 0.1),
    coronalIntensity: clampUnit(0.25 + activity * 0.65 + random() * 0.1),
  };
};

export const generateCustomStar = (parameters: CustomStarParameters): CustomStar => {
  const seed = Math.max(0, Math.trunc(parameters.seed));
  const temperatureKelvin = Math.round(
    Math.min(40_000, Math.max(2_000, parameters.temperatureKelvin)),
  );
  const spectralClass = temperatureToSpectralClass(temperatureKelvin);
  const name = parameters.name.trim() || "Untitled Star";
  return {
    star: {
      id: `custom-star-${seed}`,
      name,
      catalogName: `FORGE ${seed.toString().padStart(6, "0")}`,
      kind: parameters.kind,
      objectType: starKindDescription[parameters.kind],
      observation: {
        rightAscensionDegrees: null,
        declinationDegrees: null,
        parallaxMas: null,
        distanceParsecs: null,
        properMotionRaMasPerYear: null,
        properMotionDecMasPerYear: null,
        radialVelocityKmPerSecond: null,
        spectralType: `${spectralClass}${luminosityClass(parameters.kind)}`,
        visualMagnitude: null,
        gaiaMagnitude: null,
      },
      customization: {
        activity: clampUnit(parameters.activity),
        radius: clampUnit(parameters.radius),
        rotation: clampUnit(parameters.rotation),
        seed,
        temperatureKelvin,
      },
      source: {
        archive: "Exora Custom Generator",
        retrievedOn: new Date().toISOString().slice(0, 10),
        table: "procedural",
      },
    },
  };
};

const scaleColor = (color: Rgb, amount: number): Rgb =>
  color.map((channel) => clampUnit(channel * amount)) as unknown as Rgb;

const mixColor = (from: Rgb, to: Rgb, amount: number): Rgb =>
  from.map(
    (channel, index) => channel + (to[index] - channel) * clampUnit(amount),
  ) as unknown as Rgb;

export const generateCustomWorld = (parameters: CustomPlanetParameters): CustomWorld => {
  const radius = clampUnit(parameters.radius);
  const activity = clampUnit(parameters.activity);
  const atmosphere = clampUnit(parameters.atmosphere);
  const water = clampUnit(parameters.water);
  const seed = Math.max(0, Math.trunc(parameters.seed));
  const temperatureKelvin = Math.max(40, Math.round(parameters.temperatureKelvin));
  const radiusEarth =
    parameters.kind === "rocky"
      ? 0.45 + radius * 1.65
      : parameters.kind === "ice-giant"
        ? 2.1 + radius * 4.2
        : (0.72 + radius * 1.18) * 11.209;
  const massEarth =
    parameters.kind === "rocky"
      ? radiusEarth ** 3.1
      : parameters.kind === "ice-giant"
        ? 8 + radius * 35
        : (0.25 + radius * 9.75) * 317.83;
  const date = new Date().toISOString().slice(0, 10);
  const planet: ExoplanetProfile = {
    id: `custom-${parameters.kind}-${seed}`,
    name: parameters.name.trim() || "Untitled World",
    hostStar: "Custom star system",
    kind: parameters.kind,
    observation: {
      distanceParsecs: null,
      discoveryMethod: "Procedural synthesis",
      discoveryYear: null,
      equilibriumTemperatureKelvin: temperatureKelvin,
      hostSpectralType: "USER DEFINED",
      hostTemperatureKelvin: 5_772,
      hostRadiusSolar: 1,
      hostMassSolar: 1,
      hostLuminosityLogSolar: 0,
      massEarth,
      massJupiter: parameters.kind === "gas-giant" ? massEarth / 317.83 : null,
      orbitalPeriodDays: null,
      radiusEarth,
      radiusJupiter: parameters.kind === "gas-giant" ? radiusEarth / 11.209 : null,
      semiMajorAxisAu: null,
    },
    source: {
      archive: "Exora Custom Generator",
      retrievedOn: date,
      table: "procedural",
    },
  };

  const generated = deriveWorldRecipe(planet);
  const shared = {
    ...generated,
    axialTilt: ((parameters.axialTilt - 0.5) * Math.PI) / 2,
    rotationSpeed: 0.004 + clampUnit(parameters.rotation) * 0.062,
    atmosphere: {
      ...generated.atmosphere,
      color: mixColor(scaleColor(parameters.baseColor, 0.65), [0.72, 0.9, 1], atmosphere * 0.45),
      label: `User-defined atmosphere · ${Math.round(atmosphere * 100)}% density`,
    },
    confidence: "high" as const,
  };

  if (generated.renderer === "rocky") {
    const isHot = temperatureKelvin >= 650;
    const isCold = temperatureKelvin < 180;
    const waterLevel = isHot || water < 0.03 ? 0 : 0.22 + water * 0.32;
    const cloudCover = atmosphere * (isHot ? 0.15 : 0.82);
    const lavaStrength = isHot ? 0.2 + activity * 0.8 : 0;
    const iceCapStrength = isCold ? 0.45 + water * 0.55 : Math.max(0, water * 0.25 - 0.05);
    const craterDensity = 0.12 + activity * 0.82;
    const waterColor = mixColor([0.005, 0.06, 0.16], parameters.baseColor, 0.12);
    const highColor = mixColor(parameters.baseColor, [0.95, 0.92, 0.84], 0.52);
    return {
      planet,
      recipe: {
        ...shared,
        renderer: "rocky",
        classification: "Custom rocky world",
        rings: parameters.rings
          ? {
              bands: 3 + Math.floor(activity * 5),
              color: mixColor(parameters.baseColor, [0.85, 0.86, 0.88], 0.5),
              gapiness: 0.3 + activity * 0.4,
              innerRadius: shared.radiusSceneUnits * 1.32,
              opacity: 0.06 + atmosphere * 0.1,
              outerRadius: shared.radiusSceneUnits * (1.65 + radius * 0.4),
            }
          : null,
        surface: {
          ...generated.surface,
          lowColor: scaleColor(parameters.baseColor, 0.2),
          midColor: scaleColor(parameters.baseColor, 0.72),
          highColor,
          elevation: 0.045 + activity * 0.3,
          roughness: 1.5 + activity * 3.6,
          craterDensity,
          waterLevel,
          waterColor,
          waterColorShallow: mixColor(waterColor, highColor, 0.4),
          cloudCover,
          cloudScale: 2 + atmosphere * 3,
          cloudSpeed: 0.008 + activity * 0.04,
          lavaStrength,
          emissiveColor: isHot ? [1, 0.11, 0.008] : [0, 0, 0],
          iceCapStrength,
          windDirection: (seed % 628) / 100,
        },
        terrain: {
          ...generated.terrain,
          oceanCoverage: waterLevel,
          mountainCoverage: 0.15 + activity * 0.5,
          mountainHeight: 0.045 + activity * 0.3,
          terrainRoughness: clampUnit(activity),
          craterDensity,
          iceCoverage: iceCapStrength,
          polarIceBias: isCold ? 0.55 + water * 0.4 : 0.1,
          volcanicActivity: lavaStrength,
          lavaCoverage: isHot ? 0.25 + activity * 0.5 : 0,
          cloudCoverage: cloudCover,
          atmosphereDensity: atmosphere,
        },
        summary:
          "A user-tuned rocky world synthesized from its chosen terrain, hydrology, atmosphere, temperature, rotation, and color parameters.",
      },
    };
  }

  if (generated.renderer === "ice-giant") {
    const bandScale = 7 + activity * 13;
    const stormStrength = activity;
    const polarGlow = atmosphere * 0.75;
    return {
      planet,
      recipe: {
        ...shared,
        renderer: "ice-giant",
        classification: "Custom ice giant",
        atmosphereBands: {
          ...generated.atmosphereBands,
          deepColor: scaleColor(parameters.baseColor, 0.18),
          hazeColor: scaleColor(parameters.baseColor, 0.75),
          lightColor: mixColor(parameters.baseColor, [0.88, 0.98, 1], 0.58),
          bandScale,
          stormStrength,
          polarGlow,
          speed: 0.008 + clampUnit(parameters.rotation) * 0.04,
        },
        bandDetail: {
          ...generated.bandDetail,
          stormStrength,
          polarVariation: polarGlow,
          haze: atmosphere,
          atmosphereDepth: 0.5 + atmosphere * 0.4,
        },
        rings: {
          ...generated.rings,
          color: mixColor(parameters.baseColor, [0.82, 0.9, 1], 0.42),
          opacity: parameters.rings ? 0.08 + atmosphere * 0.22 : 0,
        },
        summary:
          "A user-tuned volatile giant synthesized from its chosen haze, storm activity, rings, temperature, rotation, and color parameters.",
      },
    };
  }

  const jetCount = 8 + Math.round(activity * 24);
  const stormStrength = activity;
  return {
    planet,
    recipe: {
      ...shared,
      renderer: "gas-giant",
      classification: "Custom gas giant",
      cloudBands: {
        ...generated.cloudBands,
        deepColor: scaleColor(parameters.baseColor, 0.16),
        midColor: scaleColor(parameters.baseColor, 0.72),
        lightColor: mixColor(parameters.baseColor, [1, 0.92, 0.75], 0.62),
        stormColor: mixColor(parameters.baseColor, [1, 0.72, 0.3], 0.68),
        contrast: 0.4 + atmosphere * 0.5,
        jetCount,
        stormScale: 2.8 + activity * 5,
        stormStrength,
        turbulence: 1.2 + activity * 3,
        speed: 0.01 + clampUnit(parameters.rotation) * 0.05,
      },
      bandDetail: {
        ...generated.bandDetail,
        bandCount: jetCount,
        bandContrast: 0.4 + atmosphere * 0.5,
        bandTurbulence: 1.2 + activity * 3,
        stormStrength,
        haze: atmosphere * 0.5,
        atmosphereDepth: 0.5 + atmosphere * 0.4,
      },
      rings: parameters.rings
        ? {
            bands: 4 + Math.floor(activity * 6),
            color: mixColor(parameters.baseColor, [0.92, 0.78, 0.58], 0.5),
            gapiness: 0.3 + activity * 0.4,
            innerRadius: shared.radiusSceneUnits * 1.24,
            opacity: 0.1 + atmosphere * 0.22,
            outerRadius: shared.radiusSceneUnits * (1.42 + radius * 0.25),
          }
        : null,
      summary:
        "A user-tuned gas giant synthesized from its chosen jet activity, storm strength, rings, temperature, rotation, and color parameters.",
    },
  };
};
